### ISSUE TITLE
About Berlin Kudamm Dataset

### ISSUE THREAD

**Issue by socome** [Nik-V9/HEAPUtil#1]
First of all, Thank you for your wonderful work.

I have a question about the Berlin Kudamm datasets.

In your letter, Berlin Kudamm dataset was explained as follows.
" ... The total traverse span is about 3 Km, where the reference traverse contains **314 frames and the query traverse has 280 frames.**"

When i checked the more details regarding the Berlin Kudamm dataset on [reference paper](https://ieeexplore.ieee.org/abstract/document/8202131), I found out that there was a difference about Berlin Kudamm datasets.  

In reference paper, Berlin Kudamm datasets was explained that the number of frames was **424 frames** as follows.

![image](https://user-images.githubusercontent.com/44772344/134767667-09c66bba-322a-4ef5-b147-572207285c2a.png)

I wonder why there is a difference. Can you explain why?

 Thank you in advance.

**Comment by Nik-V9** [comment]
Thank you for your interest in our work. 

The Berlin datasets were initially introduced in [this paper](https://nikosuenderhauf.github.io/assets/papers/rss15_placeRec.pdf). The dataset is obtained by downloading 3 Km sequences from [Mapillary](https://www.mapillary.com/), where the frames are parsed based on GPS data to get accurate ground-truth correspondences. The provided version of Berlin Kudamm is downloaded from Mapillary and uses 594 frames in total. [Berlin Kudamm GPS Data CSV](https://drive.google.com/file/d/1-EOjd0B0lz57B6vPdQwcdDXvPMMimSwo/view?usp=sharing)

I have also enquired about it from the original source within [our group](https://qcr.github.io/collection/vpr_overview/) for further info.

Please let me know if this resolves your query.

**Comment by socome** [comment]
Thank you for your answers. 

Hmm.. That was very strange.

In 'Place Recognition with ConvNet Landmarks: Viewpoint-Robust, Condition-Robust, Training-Free',  Berlin kudamm datasets was explained as follows..
" .. We ownloaded three sequences of images that exerted significant viewpoint changes and make these available to the community along with ground truth data. For example, the images of the Berlin Kurfurstendamm ¨ **(201 + 222 frames, 3 km)** .. " 

I am still confused. but thank you.

**Comment by Nik-V9** [comment]
I hope the following further info helps:

"The Berlin dataset version we used is the same as that described in [this paper](https://ieeexplore.ieee.org/document/9197360) ([arXiv](https://arxiv.org/abs/2002.03895)). It is a larger version of what was used in the [original paper](https://nikosuenderhauf.github.io/assets/papers/rss15_placeRec.pdf) with additional images prepended to both the reference and query traverses of the latter. Note: Kurfurstendamm is Kudamm.

The images are downloaded from [Mapillary](https://www.mapillary.com/app/?lat=52.490549379054784&lng=13.433286697119797&z=9.322012318326138) using the provided Matlab script, and imageList*.txt are the individual Mapillary keys for each image in the dataset."

[imageList2.txt](https://github.com/Nik-V9/HEAPUtil/files/7236621/imageList2.txt)
[Download_Sequences.m.txt](https://github.com/Nik-V9/HEAPUtil/files/7236627/Download_Sequences.m.txt)

**Comment by socome** [comment]
thank you!!
