### ISSUE TITLE
Can't install faiss-gpu>=1.7.1

### ISSUE THREAD

**Issue by mehdinejjar86** [Nik-V9/HEAPUtil#2]
When I run `pip install -r requirements.txt` I'm faced with this error.

Collecting faiss-gpu>=1.7.1
  Using cached faiss-gpu-1.7.1.post2.tar.gz (40 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/17/76/47d0cc8161f4bf988583a2839bb1e56baf09d6b80cfa472b9eba4d5f543b/faiss-gpu-1.7.1.post2.tar.gz#sha256=877478752c03678fd9b9553e4ffadca82cd337bba9bb6a939aa1c6ea561a7a58 (from https://pypi.org/simple/faiss-gpu/). Requested faiss-cpu from https://files.pythonhosted.org/packages/17/76/47d0cc8161f4bf988583a2839bb1e56baf09d6b80cfa472b9eba4d5f543b/faiss-gpu-1.7.1.post2.tar.gz#sha256=877478752c03678fd9b9553e4ffadca82cd337bba9bb6a939aa1c6ea561a7a58 (from -r requirements.txt (line 5)) has inconsistent name: filename has 'faiss-gpu', but metadata has 'faiss-cpu'
  Using cached faiss-gpu-1.7.1.post1.tar.gz (41 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/39/8d/b62bc92c8dd4b2a99d4a06b8804280f6445748b6d698eabb037e111080c7/faiss-gpu-1.7.1.post1.tar.gz#sha256=4e71f6ed035df0fee0eb40a35ce819c3f295116df15f513f18f40be8ac99be1f (from https://pypi.org/simple/faiss-gpu/). Requested faiss-cpu from https://files.pythonhosted.org/packages/39/8d/b62bc92c8dd4b2a99d4a06b8804280f6445748b6d698eabb037e111080c7/faiss-gpu-1.7.1.post1.tar.gz#sha256=4e71f6ed035df0fee0eb40a35ce819c3f295116df15f513f18f40be8ac99be1f (from -r requirements.txt (line 5)) has inconsistent name: filename has 'faiss-gpu', but metadata has 'faiss-cpu'
  Using cached faiss-gpu-1.7.1.tar.gz (40 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/51/85/7a7490dbecaea9272953b88e236a45fe8c47571a069bc28b352f0b224ea3/faiss-gpu-1.7.1.tar.gz#sha256=78b8495efd00e5e25fd0046a652f5b4587af0aebaf006fff73ac66e9610ba9fc (from https://pypi.org/simple/faiss-gpu/). Requested faiss-cpu from https://files.pythonhosted.org/packages/51/85/7a7490dbecaea9272953b88e236a45fe8c47571a069bc28b352f0b224ea3/faiss-gpu-1.7.1.tar.gz#sha256=78b8495efd00e5e25fd0046a652f5b4587af0aebaf006fff73ac66e9610ba9fc (from -r requirements.txt (line 5)) has inconsistent name: filename has 'faiss-gpu', but metadata has 'faiss-cpu'
ERROR: Could not find a version that satisfies the requirement faiss-gpu>=1.7.1 (from versions: 1.5.3, 1.6.0, 1.6.1, 1.6.3, 1.6.4, 1.6.4.post2, 1.6.5, 1.7.0, 1.7.1, 1.7.1.post1, 1.7.1.post2)
ERROR: No matching distribution found for faiss-gpu>=1.7.1

**Comment by Nik-V9** [comment]
This is a system-specific installation error. Please provide more details regarding your operating system. Also, please try `pip install faiss-gpu`.

**Comment by mehdinejjar86** [comment]
Thank you for answering me.

------------------
System Information
------------------
      Time of this report: 1/22/2022, 16:40:39
             Machine name: MW
               Machine Id: {B70F14EA-3065-4F70-910D-B739E5F4ED00}
         Operating System: Windows 11 Home 64-bit (10.0, Build 22000) (22000.co_release.210604-1628)
                 Language: English (Regional Setting: English)
      System Manufacturer: Dell Inc.
             System Model: XPS 15 7590
                     BIOS: 1.15.0 (type: UEFI)
                Processor: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 CPUs), ~2.6GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16112MB RAM
                Page File: 10947MB used, 7596MB available
              Windows Dir: C:\WINDOWS
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 240 DPI (250 percent)
       System DPI Setting: 240 DPI (250 percent)
          DWM DPI Scaling: UnKnown
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Supported
 DirectX Database Version: 1.3.2
           DxDiag Version: 10.00.22000.0001 64bit Unicode


> This is a system-specific installation error. Please provide more details regarding your operating system. Also, please try `pip install faiss-gpu`.

Collecting faiss-gpu
  Using cached faiss-gpu-1.7.1.post2.tar.gz (40 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/17/76/47d0cc8161f4bf988583a2839bb1e56baf09d6b80cfa472b9eba4d5f543b/faiss-gpu-1.7.1.post2.tar.gz#sha256=877478752c03678fd9b9553e4ffadca82cd337bba9bb6a939aa1c6ea561a7a58 (from https://pypi.org/simple/faiss-gpu/). Requested faiss-cpu from https://files.pythonhosted.org/packages/17/76/47d0cc8161f4bf988583a2839bb1e56baf09d6b80cfa472b9eba4d5f543b/faiss-gpu-1.7.1.post2.tar.gz#sha256=877478752c03678fd9b9553e4ffadca82cd337bba9bb6a939aa1c6ea561a7a58 has inconsistent name: filename has 'faiss-gpu', but metadata has 'faiss-cpu'
  Using cached faiss-gpu-1.7.1.post1.tar.gz (41 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/39/8d/b62bc92c8dd4b2a99d4a06b8804280f6445748b6d698eabb037e111080c7/faiss-gpu-1.7.1.post1.tar.gz#sha256=4e71f6ed035df0fee0eb40a35ce819c3f295116df15f513f18f40be8ac99be1f (from https://pypi.org/simple/faiss-gpu/). Requested faiss-cpu from https://files.pythonhosted.org/packages/39/8d/b62bc92c8dd4b2a99d4a06b8804280f6445748b6d698eabb037e111080c7/faiss-gpu-1.7.1.post1.tar.gz#sha256=4e71f6ed035df0fee0eb40a35ce819c3f295116df15f513f18f40be8ac99be1f has inconsistent name: filename has 'faiss-gpu', but metadata has 'faiss-cpu'
  Using cached faiss-gpu-1.7.1.tar.gz (40 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/51/85/7a7490dbecaea9272953b88e236a45fe8c47571a069bc28b352f0b224ea3/faiss-gpu-1.7.1.tar.gz#sha256=78b8495efd00e5e25fd0046a652f5b4587af0aebaf006fff73ac66e9610ba9fc (from https://pypi.org/simple/faiss-gpu/). Requested faiss-cpu from https://files.pythonhosted.org/packages/51/85/7a7490dbecaea9272953b88e236a45fe8c47571a069bc28b352f0b224ea3/faiss-gpu-1.7.1.tar.gz#sha256=78b8495efd00e5e25fd0046a652f5b4587af0aebaf006fff73ac66e9610ba9fc has inconsistent name: filename has 'faiss-gpu', but metadata has 'faiss-cpu'
  Using cached faiss-gpu-1.7.0.tar.gz (34 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/63/15/289ecf5d23f209c4c6f2f5f4db1d2b4a2be22d1fc49619354363e9367c19/faiss-gpu-1.7.0.tar.gz#sha256=9dd7f92c10a04894e2b6065eb2274aa73705381327f34da5aae5da66523a2ca6 (from https://pypi.org/simple/faiss-gpu/). Requested faiss-cpu from https://files.pythonhosted.org/packages/63/15/289ecf5d23f209c4c6f2f5f4db1d2b4a2be22d1fc49619354363e9367c19/faiss-gpu-1.7.0.tar.gz#sha256=9dd7f92c10a04894e2b6065eb2274aa73705381327f34da5aae5da66523a2ca6 has inconsistent name: filename has 'faiss-gpu', but metadata has 'faiss-cpu'
  Using cached faiss-gpu-1.6.5.tar.gz (28 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/9c/27/3477c856ea3d678619c33ae72f89ede4fbe08e9c5ba3b89a5feb3d9938b0/faiss-gpu-1.6.5.tar.gz#sha256=e08fadbfa53d1ebc6657d36ef100f12b10ffff9cdb5834fa480264daf5dfc6f9 (from https://pypi.org/simple/faiss-gpu/). Requested faiss-cpu from https://files.pythonhosted.org/packages/9c/27/3477c856ea3d678619c33ae72f89ede4fbe08e9c5ba3b89a5feb3d9938b0/faiss-gpu-1.6.5.tar.gz#sha256=e08fadbfa53d1ebc6657d36ef100f12b10ffff9cdb5834fa480264daf5dfc6f9 has inconsistent name: filename has 'faiss-gpu', but metadata has 'faiss-cpu'
  Using cached faiss-gpu-1.6.4.post2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Generating metadata for package faiss-gpu produced metadata for project name faiss-cpu. Fix your #egg=faiss-gpu fragments.
WARNING: Discarding https://files.pythonhosted.org/packages/7d/00/b3aaad408a44e4f5d87ebfcd75d0b14eeaed9fe9bc7a9f5e185ff1d503d6/faiss-gpu-1.6.4.post2.tar.gz#sha256=5d2c428af67442d1cd0317f189f842a71326e7676134fc2ada40021f127a0fd4 (from https://pypi.org/simple/faiss-gpu/). Requested faiss-cpu from https://files.pythonhosted.org/packages/7d/00/b3aaad408a44e4f5d87ebfcd75d0b14eeaed9fe9bc7a9f5e185ff1d503d6/faiss-gpu-1.6.4.post2.tar.gz#sha256=5d2c428af67442d1cd0317f189f842a71326e7676134fc2ada40021f127a0fd4 has inconsistent name: filename has 'faiss-gpu', but metadata has 'faiss-cpu'
  Using cached faiss-gpu-1.6.4.tar.gz (3.4 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Mehdi\.conda\envs\heaputil\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mehdi\\AppData\\Local\\Temp\\pip-install-9qljm3hr\\faiss-gpu_f33527c5a4c649acaeb9bfa51bf58ca1\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mehdi\\AppData\\Local\\Temp\\pip-install-9qljm3hr\\faiss-gpu_f33527c5a4c649acaeb9bfa51bf58ca1\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Mehdi\AppData\Local\Temp\pip-pip-egg-info-ki5lpenj'
       cwd: C:\Users\Mehdi\AppData\Local\Temp\pip-install-9qljm3hr\faiss-gpu_f33527c5a4c649acaeb9bfa51bf58ca1\
  Complete output (4 lines):
  running egg_info
  creating C:\Users\Mehdi\AppData\Local\Temp\pip-pip-egg-info-ki5lpenj\faiss_cpu.egg-info
  writing manifest file 'C:\Users\Mehdi\AppData\Local\Temp\pip-pip-egg-info-ki5lpenj\faiss_cpu.egg-info\SOURCES.txt'
  error: package directory 'C:\Users\Mehdi\AppData\Local\Temp\pip-install-9qljm3hr\faiss-gpu_f33527c5a4c649acaeb9bfa51bf58ca1\faiss\faiss\python' does not exist
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/56/f0/c1f2be147d97e873f74e9f5e4e31b227a52bc7d413bebfb319546440949b/faiss-gpu-1.6.4.tar.gz#sha256=576c0ade83ed0291fe5a0febc6e395c1607ebb133bb8625294a78f6a63088948 (from https://pypi.org/simple/faiss-gpu/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached faiss-gpu-1.6.3.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in c:\users\mehdi\.conda\envs\heaputil\lib\site-packages (from faiss-gpu) (1.22.1)
Building wheels for collected packages: faiss-gpu
  Building wheel for faiss-gpu (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Mehdi\.conda\envs\heaputil\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mehdi\\AppData\\Local\\Temp\\pip-install-9qljm3hr\\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mehdi\\AppData\\Local\\Temp\\pip-install-9qljm3hr\\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Mehdi\AppData\Local\Temp\pip-wheel-o2lz0om3'
       cwd: C:\Users\Mehdi\AppData\Local\Temp\pip-install-9qljm3hr\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\
  Complete output (38 lines):
  running bdist_wheel
  running build
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Mehdi\AppData\Local\Temp\pip-install-9qljm3hr\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\setup.py", line 91, in <module>
      setup(
    File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\__init__.py", line 155, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
      return run_commands(dist)
    File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
      dist.run_commands()
    File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
      cmd_obj.run()
    File "C:\Users\Mehdi\AppData\Local\Temp\pip-install-9qljm3hr\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\setup.py", line 45, in run
      build_ext.run(self)
    File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\Mehdi\AppData\Local\Temp\pip-install-9qljm3hr\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\setup.py", line 50, in build_extensions
      self._remove_flag('-Wstrict-prototypes')
    File "C:\Users\Mehdi\AppData\Local\Temp\pip-install-9qljm3hr\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\setup.py", line 58, in _remove_flag
      compiler = self.compiler.compiler
  AttributeError: 'MSVCCompiler' object has no attribute 'compiler'
  ----------------------------------------
  ERROR: Failed building wheel for faiss-gpu
  Running setup.py clean for faiss-gpu
Failed to build faiss-gpu
Installing collected packages: faiss-gpu
    Running setup.py install for faiss-gpu ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Mehdi\.conda\envs\heaputil\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mehdi\\AppData\\Local\\Temp\\pip-install-9qljm3hr\\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mehdi\\AppData\\Local\\Temp\\pip-install-9qljm3hr\\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Mehdi\AppData\Local\Temp\pip-record-_8masqo0\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Mehdi\.conda\envs\heaputil\Include\faiss-gpu'
         cwd: C:\Users\Mehdi\AppData\Local\Temp\pip-install-9qljm3hr\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\
    Complete output (42 lines):
    running install
    C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Mehdi\AppData\Local\Temp\pip-install-9qljm3hr\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\setup.py", line 91, in <module>
        setup(
      File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
        return run_commands(dist)
      File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
        dist.run_commands()
      File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\command\install.py", line 68, in run
        return orig.install.run(self)
      File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\command\install.py", line 664, in run
        self.run_command('build')
      File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\Users\Mehdi\AppData\Local\Temp\pip-install-9qljm3hr\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\setup.py", line 45, in run
        build_ext.run(self)
      File "C:\Users\Mehdi\.conda\envs\heaputil\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Users\Mehdi\AppData\Local\Temp\pip-install-9qljm3hr\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\setup.py", line 50, in build_extensions
        self._remove_flag('-Wstrict-prototypes')
      File "C:\Users\Mehdi\AppData\Local\Temp\pip-install-9qljm3hr\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\setup.py", line 58, in _remove_flag
        compiler = self.compiler.compiler
    AttributeError: 'MSVCCompiler' object has no attribute 'compiler'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Mehdi\.conda\envs\heaputil\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Mehdi\\AppData\\Local\\Temp\\pip-install-9qljm3hr\\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Mehdi\\AppData\\Local\\Temp\\pip-install-9qljm3hr\\faiss-gpu_4c13a36faf6b4d1aa7a6ab7eb090c08e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Mehdi\AppData\Local\Temp\pip-record-_8masqo0\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Mehdi\.conda\envs\heaputil\Include\faiss-gpu' Check the logs for full command output.

**Comment by Nik-V9** [comment]
Faiss Install through Pypi (pip) is not supported on Windows. Please refer to the following page: https://stackoverflow.com/questions/58957169/faiss-error-could-not-find-a-version-that-satisfies-the-requirement-faiss-from.

It is recommended that you use a conda environment for running the code on your local machine or use Google Colab.
