### ISSUE TITLE
error while extracting data.zip

### ISSUE THREAD

**Issue by HyeonJaeGil** [Nik-V9/HEAPUtil#3]
Thanks for sharing your code of your works.

I want to follow the commandline for suggested inference, 
so I tried to download your data.zip through suggested MEGA link.

But it seems that there is some errors regarding the downloaded file on Ubuntu, it displays:
```'data.zip': empty archive```

Maybe there are some errors or expiration of your MEGA link, so it would be great if you could check it.
I 'm looking forward to your reply.

Hyeonjae Gil

**Comment by Nik-V9** [comment]
Thanks for pointing this out. The issue has been resolved, and the MEGA link has been updated on the README.

Sharing the link here also for reference: https://mega.nz/file/RppWTKQR#6ZiC_TICKy4NRGXo6b5n5IVIzn7usWtF0v-EmLczMns
