### ISSUE TITLE
Oxford RobotCar dataset

### ISSUE THREAD

**Issue by ming-gray** [Nik-V9/HEAPUtil#4]
Hello, I really appreciate the work you have done, but I have problems downloading the Oxford RobotCar dataset. Can you provide the Oxford RobotCar dataset you used in your paper? Thank you so much！

**Comment by Nik-V9** [comment]
Hi, Thanks for your interest! We provide a version of the dataset here: https://github.com/AnyLoc/AnyLoc#included-datasets

**Comment by ming-gray** [comment]
Thanks for your help, I have successfully downloaded the dataset. Another question, is the oxdatapart_seg.npz the one mentioned in your paper 'For the Semantic Consistency baseline, we generate semantic segmentation masks for all reference and query images based on the Cityscapes scheme' ?
